# Generated by Django 3.2.6 on 2021-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_rename_remind_at_expenseremainder_remaind_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
