# Generated by Django 3.2.6 on 2022-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_auto_20210920_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
