# Generated by Django 3.2 on 2022-03-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaser',
            options={'managed': True, 'verbose_name': 'Our Distributor', 'verbose_name_plural': 'Our Distributors'},
        ),
    ]
