# Generated by Django 3.2.6 on 2021-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_type',
            field=models.CharField(choices=[('Installment', 'installment'), ('Full Payment', 'full_payment'), ('Unpaid', 'unpaid')], max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Installment', 'installment'), ('Full Payment', 'full_payment'), ('Unpaid', 'unpaid')], max_length=12),
        ),
    ]
