# Generated by Django 3.2.6 on 2021-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_historicalorderproduct_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='total_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorderproduct',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
    ]
