# Generated by Django 3.2.6 on 2021-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20210925_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
