# Generated by Django 3.2.6 on 2021-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'ordering': ['updated_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
