# Generated by Django 3.2.6 on 2021-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_type',
            field=models.CharField(choices=[('Partially Paid', 'installment'), ('Full Payment', 'full_payment'), ('Unpaid', 'unpaid')], max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Partially Paid', 'installment'), ('Full Payment', 'full_payment'), ('Unpaid', 'unpaid')], max_length=14),
        ),
    ]
