# Generated by Django 3.2.6 on 2021-09-26 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_customer'),
        ('Sales', '0010_auto_20210926_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='fitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='user.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='salesman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='saleman', to=settings.AUTH_USER_MODEL),
        ),
    ]
