# Generated by Django 3.2.6 on 2021-09-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_auto_20210926_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='saleman_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='saleman_amount',
            field=models.IntegerField(default=0),
        ),
    ]
