# Generated by Django 3.2.6 on 2021-09-26 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0013_auto_20210926_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fitter',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='salesman',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='saleman', to=settings.AUTH_USER_MODEL),
        ),
    ]
