# Generated by Django 3.2.6 on 2022-02-23 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0014_auto_20210926_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='fitter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='fitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
