# Generated by Django 3.2.6 on 2022-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_auto_20220223_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='fitter',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='fitter_amount',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='saleman_amount',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fitter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fitter_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='saleman_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salesman',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='gst_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
