# Generated by Django 3.2.6 on 2022-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0016_auto_20220223_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
