# Generated by Django 3.2.6 on 2021-09-16 11:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallengthproduct',
            name='product_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='historicalquantityproduct',
            name='product_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='lengthproduct',
            name='product_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='quantityproduct',
            name='product_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
