# Generated by Django 3.2.6 on 2021-09-16 12:09

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0003_auto_20210916_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
                ('purchase_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('allow_pre_order', models.BooleanField(default=False)),
                ('product_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.TextField(max_length=100, null=True)),
                ('is_never_sold', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('unit', models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Products.productcategory')),
            ],
            options={
                'verbose_name': 'historical Product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
                ('purchase_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('allow_pre_order', models.BooleanField(default=False)),
                ('product_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('is_never_sold', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], max_length=10)),
                ('product_added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='historicalquantityproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquantityproduct',
            name='product_added_by',
        ),
        migrations.RemoveField(
            model_name='historicalquantityproduct',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='lengthproduct',
            name='product_added_by',
        ),
        migrations.RemoveField(
            model_name='lengthproduct',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='quantityproduct',
            name='product_added_by',
        ),
        migrations.RemoveField(
            model_name='quantityproduct',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='HistoricalLengthProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalQuantityProduct',
        ),
        migrations.DeleteModel(
            name='LengthProduct',
        ),
        migrations.DeleteModel(
            name='QuantityProduct',
        ),
    ]
