# Generated by Django 3.2.6 on 2021-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210918_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_color',
            field=models.CharField(default='#000000CC', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='#000000CC', max_length=9),
        ),
    ]
