# Generated by Django 3.2.6 on 2021-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20210918_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit',
            field=models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], default='Quantity', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], default='Quantity', max_length=10),
        ),
    ]
