# Generated by Django 3.2.6 on 2021-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20210918_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='p_unit',
            field=models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_unit',
            field=models.CharField(choices=[('qty', 'Quantity'), ('m', 'Meters'), ('yard', 'Yards')], max_length=10),
        ),
    ]
