# Generated by Django 3.2.6 on 2021-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_historicalinventory_historicalinventoryin_historicalinventoryout_historicalinventoryreturn_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='p_unit',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Meters', 'Meters'), ('Yards', 'Yards')], max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_unit',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Meters', 'Meters'), ('Yards', 'Yards')], max_length=8),
        ),
    ]
