# Generated by Django 3.2.6 on 2021-09-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_purchaser_phone'),
        ('Products', '0013_auto_20210918_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='distributor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.purchaser'),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.purchaser'),
        ),
    ]
