# Generated by Django 3.2.6 on 2021-09-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20210921_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventoryin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinventoryout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinventoryreturn',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryreturn',
            name='product',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
