# Generated by Django 3.2.6 on 2021-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20210926_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventory',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalinventoryin',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalinventoryout',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalinventoryreturn',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryin',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryreturn',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
