# Generated by Django 3.2.6 on 2022-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_auto_20210926_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='p_unit',
            field=models.CharField(default='Unit', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_unit',
            field=models.CharField(default='Unit', max_length=8),
        ),
    ]
